-- AULA 8 - FUNCOES E AGRUPAMENTO

-- AVG - MEDIA

SELECT
    ROUND(AVG(SALARY),2) FUNC_AVG
        FROM EMPLOYEES;

-- MEDIA SALARIAL DE CADA DEPARTAMENTO

SELECT
    D.DEPARTMENT_NAME,
    ROUND(AVG(E.SALARY),2) MEDIA_SALARIAL
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME;
    
-- COUNT - CONTAGEM

SELECT
    COUNT(EMPLOYEE_ID) "FUNCIONÁRIOS ATIVOS"
        FROM EMPLOYEES;

-- CONTAR QUANTOS FUNCIONARIOS EXISTEM EM CADA DEPARTAMENTO
  
SELECT
    D.DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID)
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME
        ORDER BY 1;
    
-- MAX - MAIOR VALOR

SELECT
    MAX(SALARY) "MAIOR SALÁRIO"
        FROM EMPLOYEES;
        
-- TRAZER O MAIOR SALARIO DE CADA DEPARTAMENTO

SELECT
    D.DEPARTMENT_NAME,
    MAX(E.SALARY) "MAIOR SALÁRIO"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME
        ORDER BY 1;
    
-- MIN - MENOR VALOR    
    
SELECT
    MIN(SALARY) "MENOR SALÁRIO"
        FROM EMPLOYEES;  
  
-- TRAZER O MENOR SALARIO DE CADA DEPARTAMENTO  
  
SELECT
    D.DEPARTMENT_NAME,
    MIN(E.SALARY) "MENOR SALÁRIO",
    MAX(E.SALARY) "MAIOR SALÁRIO"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME
        ORDER BY 1;  
  
-- SUM - SOMA

SELECT
    SUM(SALARY) "SOMA DOS SALÁRIOS"
        FROM EMPLOYEES;
  
-- A SOMA DOS SALÁRIOS DE CADA DEPARTAMENTO

SELECT
    D.DEPARTMENT_NAME,
    SUM(E.SALARY) "SOMA DOS SALÁRIOS"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID =  D.DEPARTMENT_ID
        GROUP BY D.DEPARTMENT_NAME
        ORDER BY 2;

-- DESVIO PADRAO

SELECT
    STDDEV(SALARY) "DESVIO PADRÃO GERAL"
        FROM EMPLOYEES;
  
-- DESVIO PADRAO DE CADA DEPARTAMENTO

SELECT
    D.DEPARTMENT_NAME,
    STDDEV(E.SALARY) "DESVIO PADRÃO"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY D.DEPARTMENT_NAME
        ORDER BY 2;

  
-- VARIANCIA

SELECT
    VARIANCE(SALARY) "VARIANCIA GERAL"
        FROM EMPLOYEES;
  
  
-- VARIANCIA DE SALARIO DE CADA DEPARTAMENTO  
  
SELECT
    D.DEPARTMENT_NAME,
    ROUND(VARIANCE(E.SALARY),2) "VARIANCIA"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME
        ORDER BY 2;

-- CLAUSULA HAVING

SELECT
    D.DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID) QTD_FUNC
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME        
        HAVING COUNT(E.EMPLOYEE_ID) >=2
        ORDER BY 2;

-- MOSTRA SE O CUNCIONARIO POSSUI PERCENTUAL DE COMISSAO

SELECT
    FIRST_NAME,
    CASE
        WHEN COMMISSION_PCT IS NULL
        THEN 'NÃO É VENDEDOR'
        ELSE 'VENDEDOR'
    END STATUS_COMISSAO
FROM EMPLOYEES;
        
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    