-- EXERCICIOS AULA 8

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- EX 1

SELECT
    COUNT(EMPLOYEE_ID) "QUANDIDADE DE FUNCIONARIOS"
        FROM EMPLOYEES;
        
-- EX 2

SELECT
    DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID) "QUANTIDADE DE FUNCIONARIOS"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        GROUP BY DEPARTMENT_NAME
        ORDER BY 1;
        
-- EX 3

SELECT
    D.DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID) "QUANTIDADE DE FUNCIONARIOS"
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        HAVING MAX (E.DEPARTMENT_ID) >= 50 
        GROUP BY DEPARTMENT_NAME 
        ORDER BY 1;
        
        
-- EX 4

SELECT
    MANAGER_ID,
    COUNT(EMPLOYEE_ID) "QUANTIDADE DE FUNCIONARIOS"
        FROM EMPLOYEES
        GROUP BY MANAGER_ID
        HAVING MANAGER_ID IS NOT NULL;
        
SELECT
    E.MANAGER_ID,
    E2.FIRST_NAME,
    COUNT(E.EMPLOYEE_ID) AS QTD_FUNC_SUBORDINADOS
        FROM EMPLOYEES E INNER JOIN EMPLOYEES E2 
        ON E.MANAGER_ID = E2.EMPLOYEE_ID
        GROUP BY E.MANAGER_ID, E2.FIRST_NAME
        ORDER BY 1;

        
    
    
    
    
    
        